language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-24.0.0
    - build-tools-24.0.0
    - android-24
    - platform-tools
language:node_js
node_js:
  - "7"
  - "6"
  - "4"
install:
  # need to also set up Node environment
  - node --version
  - npm install
  - npm install -g gulp
script:
  - gulp once
after_success:
  - gulp coveralls
